name: Inclusive Organization
on:
  push:
    branches: master
jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite contributor to the organization
        uses: lekterable/inclusive-organization-action@v1.1.0
        with:
          organization: DeCodeCafe Community
          comment: Thank you so much for your contribution! Your Contribution is very important to us!
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
